### ISSUE TITLE
how to create hudgui?

### ISSUE THREAD

**Issue by faithful112** [lukflug/PanelStudio#10]
how to make hudgui render?
I followed the example and used gamesenses resources
in clickgui itself the component has been rendered, but when the gui is closed it disappears

please add more examples using hudgui

**Comment by lukflug** [comment]
More extensive examples are comming with PanelStudio 0.2.0.
But have you called `render` and `handleKeyEvent` even when the GUI is closed, i.e. calling these methods when rendering the overlay and when typing a key respectively. The key event can be left out, if your HUD modules don't accept key input (i.e. when you're not using anything like the TabGUI).
