### ISSUE TITLE
Add examples to README.md

### ISSUE THREAD

**Issue by ghost** [lukflug/PanelStudio#2]
Could you add some examples of basic ClickGUIs in the README.md? Thanks!

**Comment by lukflug** [comment]
If you are looking for basic examples for GUI Themes, consult the Themes provided by the library:
* https://github.com/lukflug/PanelStudio/blob/main/src/main/java/com/lukflug/panelstudio/theme/GameSenseTheme.java
* https://github.com/lukflug/PanelStudio/blob/main/src/main/java/com/lukflug/panelstudio/theme/ClearTheme.java

**Comment by lukflug** [comment]
Readme now has a more detailed explanation
