### ISSUE TITLE
PanelStudio Wont Open

### ISSUE THREAD

**Issue by NinjacadoOfficial** [lukflug/PanelStudio#4]
I've downloaded the jars, but they wont open. Did I do something wrong?

Edit: Nevermind, I didn't realise it was a mod, not a program.

**Comment by lukflug** [comment]
From what I understood you tried to double clicked the jars. This isn't the intended behaviour. These aren't executable jars. These jars are to be imported as libraries to your client. The client jar will then include the contents of the PanelStudio jar. The code is then executed when opening Minecraft with the client jar in the mods folder.

**Comment by yagel15637** [comment]
It's just as the GameSense moto says:
"If it's an error, it's a user error." -lukflug

**Comment by srgantmoomoo** [comment]
this issue is just embarrassing lol

**Comment by k0nnect** [comment]
idiot

**Comment by yagel15637** [comment]
saying what we won't. 🙏

**Comment by ghost** [comment]
iq issue
