### ISSUE TITLE
1.16.5 Text is getting mad

### ISSUE THREAD

**Issue by f1den** [lukflug/PanelStudio#44]
After compiling jar for 1.16.5 forge, i entered  the menu and saw this sh*t:
![image](https://github.com/lukflug/PanelStudio/assets/56506428/b36abe61-24f1-4356-9809-ff88486df3c5)
How to fix this bad text.

**Comment by lukflug** [comment]
I don't see what you're referring to. This is 100% expected behavior as far as I can see.

**Comment by f1den** [comment]
i am talking about functions. they are named like  ASOIDFGhjsdfogi sd i jsdf.

why is it and how to make it normal

**Comment by f1den** [comment]
i just saw
  public static void init() {
    for (Category category : values()) {
      int count = random.nextInt(6) + 5;
      for (int i = 0; i < count; i++) {
        if (category != OTHER && category != HUD)
          category.modules.add(generateRandomModule()); 
      } 
    } 
  }
  
  :DD
  
  On screen shots i saw real l modules, and 1 more question. Where i can change theme?
