### ISSUE TITLE
[Important] Render Gui issue 

### ISSUE THREAD

**Issue by f1den** [lukflug/PanelStudio#45]
I found bug. I open GUI, Crosshair and other is showing. I close it all turning bad.

![image](https://github.com/lukflug/PanelStudio/assets/56506428/2c0b8ffc-fc4c-424a-976e-d317f7e5dfb3)

![image](https://github.com/lukflug/PanelStudio/assets/56506428/435a3007-8ebe-470e-bcbd-0e0ed6a866de)

**Comment by lukflug** [comment]
Is this the unmodified example mod? Can you provide steps required to reproduce this issue?

**Comment by f1den** [comment]
i downloaded, opened in intellij commented random module generator. thats all. (usingreobf shadowjar). Layout csgoSearch + theme impact

**Comment by f1den** [comment]
I tried to download standard and just gradlew build = same issue.
Tested Minecraft Forge + Optifine and raw Forge

**Comment by f1den** [comment]
Got fixed
@SubscribeEvent
	public void onRender (RenderGameOverlayEvent.Post event) {
		if (inited) {
			if (gui.getGUI().getGUIVisibility().isOn() || gui.getGUI().getHUDVisibility().isOn()){
				if (event.getType()==RenderGameOverlayEvent.ElementType.HOTBAR){
					gui.render();
				}
			}
		} else {
			Category.init();
			Category.OTHER.modules.add(new ClickGUIModule());
			Category.OTHER.modules.add(new HUDEditorModule());
			Category.HUD.modules.add(new TabGUIModule());
			Category.HUD.modules.add(new WatermarkModule());
			Category.HUD.modules.add(new LogoModule());
			gui=new ClickGUI();
			inited=true;
		}
	}
