### ISSUE TITLE
gg, compiled mod wont open (cum issue)

### ISSUE THREAD

**Issue by faithful112** [lukflug/PanelStudio#7]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Cum Hack (cumhack)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.renderer.GLAllocation.createDirectFloatBuffer(I)Ljava/nio/FloatBuffer;
	at com.lukflug.panelstudio.mc12.GLInterface.<clinit>(GLInterface.java:37)
	at com.newcummer.cumhack.gui.Gui.<init>(Gui.java:32)
	at com.newcummer.cumhack.Main.init(Main.java:52)

how do i fix this

**Comment by lukflug** [comment]
what minecraft and forge version are you using? are you running this through the IDE or with the launcher? did you reobfuscate the jar?

**Comment by faithful112** [comment]
i used launcher to launch.
1.12.2, forge - 14.23.5.2854, jaba - amazon corretto 1.8.0_282.
reobfuscate? no I just compiled my project in intellij and used the jar file with the postmark "all"

**Comment by lukflug** [comment]
can you send me your `build.gradle` file

**Comment by faithful112** [comment]
github dont support that file type

**Comment by faithful112** [comment]
buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.3'
    }
}
        
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'com.github.johnrengelman.shadow'

version = '228'
group = 'com.newcummer.cumhack'
archivesBaseName = 'cumhack'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }
        server {
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

repositories {
    maven {
        name = 'lukflug'
        url = 'https://lukflug.github.io/maven'
    }
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2854'
}

dependencies {
    compile('com.lukflug:panelstudio:0.1.8')
    compile('com.lukflug:panelstudio-mc12:0.1.8')
}

shadowJar {
    dependencies {
        include(dependency('com.lukflug:panelstudio'))
        include(dependency('com.lukflug:panelstudio-mc12'))
    }
}

jar.finalizedBy('reobfJar')

build.dependsOn(shadowJar)

**Comment by lukflug** [comment]
Try using the newer 20180814 mappings.

**Comment by faithful112** [comment]
how

**Comment by lukflug** [comment]
Replace this line:
```
mappings channel: 'snapshot', version: '20171003-1.12'
```
by this:
```
mappings channel: 'snapshot', version: '20180814-1.12'
```

**Comment by faithful112** [comment]
holy cum! it did not help

**Comment by lukflug** [comment]
Ok, it seems you reobfuscated your client code, but didn't reobfuscate the included PanelStudio classes. Idk exactly how to do this on ForgeGradle 3.x, but try replacing `jar.finalizedBy('reobfJar')`, by:
```
reobf {
    shadowJar {
        mappingType = 'SEARGE'
        classpath = sourceSets.main.compileClasspath
    }
}
```
if that doesn't work add, in addtion to the code above:
```
sahdowJar.finalizedBy('reobfJar')
```

**Comment by faithful112** [comment]
A problem occurred evaluating root project 'Cumhack'.
> Could not set unknown property 'mappingType' for task ':reobfShadowJar' of type net.minecraftforge.gradle.userdev.tasks.RenameJarInPlace.

**Comment by lukflug** [comment]
This build.gradle should work:
```
buildscript {
  repositories {
    maven { url = 'https://files.minecraftforge.net/maven' }
    jcenter()
    mavenCentral()
  }
  dependencies {
    classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
  }
}

apply plugin: 'net.minecraftforge.gradle'

version = '228'
group = 'com.newcummer.cumhack'
archivesBaseName = 'cumhack'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.

minecraft {
  mappings channel: 'snapshot', version: '20180814-1.12'
  runs {
    client {
      workingDirectory project.file('run')
      property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
      property 'forge.logging.console.level', 'debug'
    }
    server {
      property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
      property 'forge.logging.console.level', 'debug'
    }
  }
}

repositories {
  maven {
    name = 'lukflug'
    url = 'https://lukflug.github.io/maven'
  }
  mavenCentral()
}

configurations {
  embed
  compile.extendsFrom(embed)
}

dependencies {
  minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2854'
  embed('com.lukflug:panelstudio:0.1.8')
  embed('com.lukflug:panelstudio-mc12:0.1.8')
}

jar {
  from configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
}

jar.finalizedBy('reobfJar')
```

**Comment by faithful112** [comment]
HOLY SHIITTTTTT ITS STARTED!!! THANK YOU VERY MUCH
